wandb_version: 1

DNASwan/coeff:
  desc: null
  value: 1
DNASwan/embedding_size:
  desc: null
  value: 10
DNASwan/hidden_size:
  desc: null
  value: 16
DNASwan/input_size:
  desc: null
  value: 5
DNASwan/layer_dropout:
  desc: null
  value: 0
DNASwan/max_len:
  desc: null
  value: 1000
DNASwan/mlp_dropout:
  desc: null
  value: 0
DNASwan/norm:
  desc: null
  value: None
DNASwan/output_size:
  desc: null
  value: 49
DNASwan/prenorm:
  desc: null
  value: None
DNASwan/track_size:
  desc: null
  value: 1
Deepsea/output_size:
  desc: null
  value: 49
Linformer/clf_dim:
  desc: null
  value: 16
Linformer/dim_in:
  desc: null
  value: 5
Linformer/dim_out:
  desc: null
  value: 16
Linformer/heads:
  desc: null
  value: 2
Linformer/layers:
  desc: null
  value: 2
Linformer/max_len:
  desc: null
  value: 20000
Linformer/name:
  desc: null
  value: linformer
Linformer/output_size:
  desc: null
  value: 49
Mega/clf_dim:
  desc: null
  value: 16
Mega/dim_in:
  desc: null
  value: 5
Mega/dim_out:
  desc: null
  value: 16
Mega/heads:
  desc: null
  value: 2
Mega/layers:
  desc: null
  value: 2
Mega/max_len:
  desc: null
  value: 20000
Mega/name:
  desc: null
  value: mega
Mega/output_size:
  desc: null
  value: 49
Nystromformer/clf_dim:
  desc: null
  value: 16
Nystromformer/dim_in:
  desc: null
  value: 5
Nystromformer/dim_out:
  desc: null
  value: 16
Nystromformer/heads:
  desc: null
  value: 2
Nystromformer/layers:
  desc: null
  value: 2
Nystromformer/max_len:
  desc: null
  value: 20000
Nystromformer/name:
  desc: null
  value: nystromer
Nystromformer/output_size:
  desc: null
  value: 49
S4/clf_dim:
  desc: null
  value: 16
S4/dim_in:
  desc: null
  value: 5
S4/dim_out:
  desc: null
  value: 16
S4/heads:
  desc: null
  value: 2
S4/layers:
  desc: null
  value: 2
S4/max_len:
  desc: null
  value: 20000
S4/name:
  desc: null
  value: s4
S4/output_size:
  desc: null
  value: 49
Transformer/clf_dim:
  desc: null
  value: 16
Transformer/dim_in:
  desc: null
  value: 5
Transformer/dim_out:
  desc: null
  value: 16
Transformer/heads:
  desc: null
  value: 1
Transformer/layers:
  desc: null
  value: 1
Transformer/max_len:
  desc: null
  value: 1000
Transformer/name:
  desc: null
  value: transformer
Transformer/output_size:
  desc: null
  value: 49
_wandb:
  desc: null
  value:
    cli_version: 0.13.0
    framework: huggingface
    huggingface_version: 4.26.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val_auroc
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_roc
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    python_version: 3.9.12
    start_time: 1691929435.259513
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.9.12
      5: 0.13.0
      6: 4.26.0
      8:
      - 5
training/batch_size:
  desc: null
  value: 32
training/device:
  desc: null
  value: cuda
training/learning_rate:
  desc: null
  value: 0.0003
training/n_cycles:
  desc: null
  value: 0.5
training/n_epochs:
  desc: null
  value: 20
training/n_warmup_steps:
  desc: null
  value: 50000
training/patience:
  desc: null
  value: -1
training/pretrained:
  desc: null
  value: true
training/save_every:
  desc: null
  value: 2500
training/swa_lrs:
  desc: null
  value: -1
training/weight_decay:
  desc: null
  value: 0.0003
