command:
  - python3
  - hyper_search.py
method: bayes
metric:
  goal: maximize
  name: val_auroc
parameters:
  batch_size:
    values:
      - 64
      - 128
  embedding_size:
    values:
      - 5
  hidden_size:
    values:
      - 16
  coeff:
    values:
      - 1
      - 1.3
      - 1.4
  layer_dropout:
    values:
      - 0
  learning_rate:
    values:
      - 0.0003
      - 0.0008
  mlp_dropout:
    values:
      - 0
  n_epochs:
    values:
      - 15
      - 20
      - 25
  n_warmup_steps:
    values:
      - 50000
  norm:
    values:
      - None
  prenorm:
    values:
      - None
  track_size:
    values:
      - 1
  weight_decay:
    values:
      - 0.0003
program: hyper_search.py